project_identifier: catrobat
api_key: 6c9a3f10bd747ea3198c0bb9b651d9ab
base_url: http://api.crowdin.net
base_path: /home/catroweb/Workspace/catroweb
preserve_hierarchy: true

files:
  -
    source: '/include/xml/lang/en/**/*.xml'                                   #source files filter
    translation: '/include/xml/lang/%locale%/**/%original_file_name%'  #where translations live
    update_option: 'update_as_unapproved'
    languages_mapping:
      locale:
        'ar': 'ar'
        'bs': 'bs'
        'de': 'de'
        'es-ES': 'es'
        'fr': 'fr'
        'hr': 'hr'
        'hu': 'hu'
        'it': 'it'
        'ja': 'ja'
        'ko': 'ko'
        'nl': 'nl'
        'no': 'no'
        'pl': 'pl'
        'pt-PT': 'pt'
        'ro': 'ro'
        'ru': 'ru'
        'sl': 'sl'
        'tr': 'tr'

