project_identifier: catrobat
api_key: 6c9a3f10bd747ea3198c0bb9b651d9ab
base_url: http://api.crowdin.net
base_path: /home/catroweb/Workspace/catroweb
preserve_hierarchy: true

files:
  -
    source: '/include/xml/lang/en/**/*.xml'                                   #source files filter
    translation: '/include/xml/lang/%two_letters_code%/**/%original_file_name%'  #where translations live
      
